gen:
  fullscreen: on
  winres:
    width: 1440
    height: 900
  width: 1920
  height: 1080
  fps: 60
  title: Undervoid
  tilesize: 64
  titledim: [535, 65]
  music: on
  sound: on
  spawn_max_dist: 1000
  spawn_min_dist: 500
  spawn_max: 8
  spawn_min: 5
  mob_max: 8

lvl:
  pieces: 3
  tiles_wide: 64
  tiles_high: 32
  rift_usable_distance: 100

layer:
  floor: 0
  grave: 0
  wall: 1
  item: 1
  player_move: 1
  player: 2
  mob: 2
  bullet: 3
  vfx: 4
  cursor: 5

player:
  size: GEN["TILESIZE"] * 2
  speed_mult: 12
  rot_speed: 250
  hit_rect: [0, 0, 35, 35]
  hand_offset: [65, 25]
  dmg_mult: 2.0
  hp: 100

weapon:
  vbullet:
    speed: 1500
    life: 750
    rate: 150
    spread: 5
    dmg: 10
    fx_life: 40

mob:
  thrall:
    speed: [13, 14, 15]
    hp: 75
    dmg: 15
    knockback: 20
    player_radius: 1000
    drop_chance: 0.75
    dmg_rate: 150
  sleeper:
    speed: [13, 14, 15]
    hp: 100
    dmg: 20
    knockback: 20
    player_radius: 1000
    drop_chance: 0.75
    dmg_rate: 150

items:
  potions:
    red:
      hp: 0.20
  bob_range: 15
  bob_speed: 0.4

img:
  title: undervoidtitle.png
  icon: undervoidicon.png
  rift: rift01.png
  cursor:
  - cursor01.png
  - cursor02.png
  - cursor03.png
  - cursor03.png
  - cursor02.png
  - cursor01.png
  player:
    voidwalker:
      stance:
        magic: voidwalker_magic.png
        coachgun: voidwalker_coachgun.png
      move:
      - voidwalkermove01.png
      - voidwalkermove02.png
      - voidwalkermove01.png
      - voidwalkermove03.png
      - voidwalkermove04.png
      - voidwalkermove03.png
    pilgrim:
      stance:
        magic: pilgrim_magic.png
        coachgun: pilgrim_coachgun.png
      move:
      - pilgrimmove01.png
      - pilgrimmove02.png
      - pilgrimmove01.png
      - pilgrimmove03.png
      - pilgrimmove04.png
      - pilgrimmove03.png
    lizardwizard:
      stance:
        magic: lizardwizard_magic.png
        coachgun: lizardwizard_coachgun.png
      move:
      - lizardwizardmove01.png
      - lizardwizardmove02.png
      - lizardwizardmove01.png
      - lizardwizardmove03.png
      - lizardwizardmove04.png
      - lizardwizardmove03.png
  mob:
    thrall:
      main: thrall.png
      grave:
      - thrallgrave01.png
      - thrallgrave02.png
      - thrallgrave03.png
    sleeper:
      main: sleeper.png
      grave:
      - sleepergrave01.png
      - sleepergrave02.png
  items:
    redpotion: potion01.png
    coin: coin01.png
    bag: bag01.png
  bullets:
    void:
      bullet: voidbullet02.png
      fx:
      - voiddust01.png
      - voiddust02.png
      - voiddust03.png
      - voiddust04.png
  wall:
    voidwall: voidwall.png
  floor:
    dungeon:
    - dungeonfloor01.png
    - dungeonfloor02.png
    - dungeonfloor03.png
    - dungeonfloor04.png
    - dungeonfloor05.png
    grass:
    - grassfloor01.png
    snow:
    - snowfloor01.png
    - snowfloor02.png
    - snowfloor03.png
    - snowfloor04.png
    - snowfloor05.png
    void:
    - voidfloor01.png
    - voidfloor02.png
    - voidfloor03.png

music:
  leavinghome: Leaving Home.mp3
  voidwalk: voidwalk.wav

sounds:
  growl01: growl01.wav
  treasure01: treasure01.wav
  treasure02: treasure02.wav
  treasure03: treasure03.wav
  woadbear01: woadbear01.wav
  wave01: wave01.wav
  hit01: hit01.wav
  hit02: hit02.wav
  hit03: hit03.wav

hit_sounds:
- hit01
- hit02
- hit03

colors:
  white: [255, 255, 255]
  black: [0, 0, 0]
  darkgrey: [40, 40, 40]
  lightgrey: [100, 100, 100]
  green: [0, 255, 0]
  red: [255, 0, 0]
  yellow: [255, 255, 0]
  darkblue: [0, 0, 50]
  mediumvioletred: [199, 21, 133, 255]

void_colors:
- black
- gray0
- gray1
- darkmagenta
- darkviolet
- purple4
- mediumvioletred
- deepskyblue4

map:
  basic:
  - map_gen01.txt
  - map_gen02.txt
  - map_gen03.txt
  - map_gen04.txt
  - map_gen05.txt
  - map_gen06.txt
